export const SET_ALLJOURNALS = 'SET_ALLJOURNALS';
export const ADD_JOURNAL = 'ADD_JOURNAL';
export const SET_CURRENTJOURNAL = 'SET_CURRENTJOURNAL';
export const UPDATE_JOURNAL = 'UPDATE_JOURNAL';
export const DELETE_JOURNAL = 'DELETE_JOURNAL';
